tag: dev

apinotas:
  replicaCount: 1
  image: okteto.dev/apinotas

notasMongoUrl: mongodb://mongo/test

AWS_ACCESS_KEY_SERVICIO_NOTAS: notassedeberiasobreescribirconelhelmdeloktetopipeline
AWS_SECRET_KEY_SERVICIO_NOTAS: notassedeberiasobreescribirconelhelmdeloktetopipeline2
