apiVersion: v1
kind: Secret
metadata:
  name: mongodbservicionotas
  labels:
    app.kubernetes.io/component: mongodbservicionotas
    {{- include "backendnotas.labels" . | nindent 4 }}
type: Opaque
data:
  mongo_url_servicio_notas: {{ .Values.notasMongoUrl | b64enc }}